language: go
go:
 - 1.7

services:
  -postgresql
before_script:
  - psql -c 'create database ngorm;' -U postgres

before_install:
 - go get -t -v
 - go get github.com/mattn/goveralls
script:
 - $HOME/gopath/bin/goveralls -service=travis-ci -repotoken=$COVERALLS
